name: Provision GitHub Teams

on:
  workflow_dispatch:
  push:
    paths:
      - terraform/github-teams/**

jobs:
  terraform-teams:
    name: Provision Org Teams
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/github-teams

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
